# Generated by Django 3.1.7 on 2024-03-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Buddy_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Study_Buddy_App.subject')),
            ],
        ),
    ]
