# Generated by Django 3.1.7 on 2024-03-28 21:43

import Study_Buddy_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Buddy_App', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=Study_Buddy_App.models.default_deadline),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
