# Generated by Django 3.1.7 on 2024-03-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Buddy_App', '0005_day_tasksession_topicsession'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('name',)},
        ),
    ]
