# Generated by Django 3.1.7 on 2024-03-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Buddy_App', '0007_auto_20240329_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10, unique=True),
        ),
    ]
