# Generated by Django 3.1.7 on 2024-03-29 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Buddy_App', '0008_auto_20240329_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='tasksession',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='topicsession',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='tasksession',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Study_Buddy_App.task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicsession',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Study_Buddy_App.topic'),
            preserve_default=False,
        ),
    ]
