# Generated by Django 3.1.7 on 2024-03-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Buddy_App', '0010_auto_20240330_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
