# Generated by Django 5.0.2 on 2024-04-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Study_Buddy_App", "0012_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasksession",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="topicsession",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
